[setup]
pkgs = ["python312", "gcc", "pkg-config", "cairo", "pango", "zlib", "libjpeg"]

[install]
cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]