[setup]
pkgs = [
  "python312",
  "gcc",
  "pkg-config",
  "cmake",
  "meson",
  "ninja",
  "cairo",
  "cairo.dev",
  "pango",
  "pango.dev",
  "glib",
  "glib.dev",
  "pixman",
  "zlib",
  "libjpeg"
]

[install]
cmds = [
  "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"
]
