[phases.setup]
nixPkgs = [
  "python312",
  "gcc",
  "pkg-config",
  "cmake",
  "cairo",
  "cairo.dev",
  "glib",
  "freetype",
  "fontconfig",
  "xorg.libX11",
  "xorg.libXrender",
  "xorg.libXext",
  "xorg.libxcb"
]

[phases.install]
cmds = [
  "export PKG_CONFIG_PATH=$(find /nix/store -type d -path '*/lib/pkgconfig' | tr '\\n' ':')",
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:3000 --timeout 120 --workers 2 --worker-tmp-dir /dev/shm"
