[phases.setup]
nixPkgs = [
  "python312",
  "gcc",
  "pkg-config",

  "cairo",
  "glib",
  "freetype",
  "fontconfig",

  "xorg.libX11",
  "xorg.libXrender",
  "xorg.libXext",

  "xorg.libxcb",
  "xorg.xcbutil",
  "xorg.xcbutilwm",
  "xorg.xcbutilimage",
  "xorg.xcbutilkeysyms",
  "xorg.xcbutilrenderutil"
]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:3000 --timeout 120 --workers 2 --worker-tmp-dir /dev/shm"
