[variables]
NIXPACKS_PYTHON_VERSION = "3.12"

[setup]
pkgs = [
  "python312",
  "gcc",
  "pkg-config",
  "cairo",
  "cairo.dev",
  "pango",
  "pango.dev",
  "zlib",
  "libjpeg"
]

[install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install -r requirements.txt"
]
